# To filter by user flair in comments (useful for some subreddits)
allowed_flairs: 
- 'Juez'
- 'Abogado'
- 'Estudiante'
- 'Experto en Seguros'
- 'Moderador - Abogado'
- 'Contador (puto)'
- 'Penalista'
- 'Moderador - Abogado Ausente'
- 'Estudiante no verificado'
- 'Moderador - Estudiante'
- 'Abogado no verificado'
- 'Abogado Verificado - CABA/PBA'
- 'Estudiante verificado'
- 'Abogado Verificado - Mendoza'
- 'Abogado Verificado - Santa Fe'
- 'Abogado Verificado'
- 'Estudiante Verificado - Córdoba'
- 'Estudiante Verificado'
- 'Estudiante Verificado - MPF'
- 'Estudiante Verificado - UBA'
- 'Abogada Verificada'
- 'Estudiante Verificada'